/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IEntryPointInterface extends Interface {
  getFunction(nameOrSignature: "validateUserOp"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "validateUserOp",
    values: [
      AddressLike,
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "validateUserOp",
    data: BytesLike
  ): Result;
}

export interface IEntryPoint extends BaseContract {
  connect(runner?: ContractRunner | null): IEntryPoint;
  waitForDeployment(): Promise<this>;

  interface: IEntryPointInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  validateUserOp: TypedContractMethod<
    [
      sender: AddressLike,
      nonce: BigNumberish,
      initCode: BytesLike,
      callData: BytesLike,
      callGasLimit: BigNumberish,
      verificationGasLimit: BigNumberish,
      preVerificationGas: BigNumberish,
      maxFeePerGas: BigNumberish,
      maxPriorityFeePerGas: BigNumberish,
      paymasterAndData: BytesLike,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "validateUserOp"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      nonce: BigNumberish,
      initCode: BytesLike,
      callData: BytesLike,
      callGasLimit: BigNumberish,
      verificationGasLimit: BigNumberish,
      preVerificationGas: BigNumberish,
      maxFeePerGas: BigNumberish,
      maxPriorityFeePerGas: BigNumberish,
      paymasterAndData: BytesLike,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
